# Generated by Django 3.0.4 on 2020-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200321_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.IntegerField(default=1000),
        ),
    ]
