# Generated by Django 3.0.4 on 2020-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200329_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Popisek profilu můžete změnit ', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png', max_length=300),
        ),
    ]
