# Generated by Django 3.0.4 on 2020-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='about',
            field=models.TextField(default='sample text'),
        ),
    ]
