# Generated by Django 3.0.4 on 2020-03-23 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20200321_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('about', models.TextField(default='sample text')),
                ('image', models.ImageField(default='default.png', upload_to='item_pics')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('date_edited', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
