# Generated by Django 3.0.4 on 2020-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_itemowned'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ItemOwned',
        ),
    ]
