# Generated by Django 3.0.4 on 2020-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200329_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://ih1.redbubble.net/image.770583657.2123/flat,750x1000,075,f.u1.jpg', max_length=300),
        ),
    ]
