# Generated by Django 3.0.4 on 2020-03-30 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200329_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ItemOwned',
        ),
    ]
