# Generated by Django 3.0.4 on 2020-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200330_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://i.pinimg.com/originals/c4/59/ac/c459ac0f3a776c5b03e2b9595e611288.jpg', max_length=300),
        ),
    ]
